### ISSUE TITLE
PhpStorm 2023.1 RC

### ISSUE THREAD

**Issue by CrazyBoy49z** [hsz/intellij-foldable-project-view#55]
Not compatible with the version of your running IDE

**Comment by vvanglro** [comment]
> [#56 (comment)](https://github.com/hsz/intellij-foldable-project-view/issues/56#issuecomment-1492133984)

Your branch is working normally. Thank you.

**Comment by hsz** [comment]
Please use the EAP channel to get the 2.0.0-EAP.1 release of the Foldable Project View plugin 👉 https://plugins.jetbrains.com/plugins/eap/17288
