### ISSUE TITLE
PhpStorm 2023.2 EAP doesn't work

### ISSUE THREAD

**Issue by CrazyBoy49z** [hsz/intellij-foldable-project-view#59]
PhpStorm 2023.2 EAP doesn't work

**Comment by shuohao** [comment]
IDEA 2023.2 plz

**Comment by vvanglro** [comment]
Refer to this fork: https://github.com/pavankjadda/intellij-foldable-project-view/

**Comment by hsz** [comment]
Please use the EAP channel to get the 2.0.0-EAP.1 release of the Foldable Project View plugin 👉 https://plugins.jetbrains.com/plugins/eap/17288
